# Generated by Django 5.1.4 on 2025-08-22 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cow breed', max_length=100, unique=True)),
                ('expected_milk_quality', models.TextField(help_text='Description of the typical milk quality from this breed.')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_photo', models.ImageField(blank=True, null=True, upload_to='farmer_photos/')),
                ('name', models.CharField(max_length=150)),
                ('rf_no', models.CharField(help_text='Registration or Reference number for the farmer', max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('total_cows', models.PositiveIntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milk_data.district')),
            ],
        ),
        migrations.CreateModel(
            name='MilkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_milk', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='milk_data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_photo', models.ImageField(blank=True, null=True, upload_to='cow_photos/')),
                ('cow_name', models.CharField(help_text='A unique name or ID for the cow', max_length=100)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milk_data.breed')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='milk_data.supplier')),
            ],
        ),
    ]
