# Generated by Django 5.1.3 on 2025-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='expected_milk_quality',
            field=models.IntegerField(help_text='Description of the typical milk quality from this breed.'),
        ),
    ]
